### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by hrvstr** [lformella/xdcc-grabscher#16]
I don't know if this is the right place for feature requests, so feel free to move/close this issue.

features:
- be able to highlight the packetname in the webfrontend. (to copy/paste, google, search imdb, etc)
- a function to cancel active downloads, for when a packet turns out to be something else.
- an option to load the local search results on multiple pages because the browser often freezes for 10-15 seconds when entering search terms with 5000+ results.
- an option to set a custom/more useful startpage than the dashboard
- an option to hide the botlist in the local search tab, useful for when viewing on small displays

I know this is kind of an overcharge but i would like to know if you plan on adding any of this features. I also would like to contribute but I am afraid I could only help design-wise (as this is my profession) and maybe a little html/css.

anyway, thanks for this amazing software!

**Comment by lformella** [comment]
- be able to highlight the packetname in the webfrontend. (to copy/paste, google, search imdb, etc)

Can you be more specific?
- a function to cancel active downloads, for when a packet turns out to be something else.

You can click on the icon of a downloading packet and XG will stop the download process and clean up temporary files.
- an option to load the local search results on multiple pages because the browser often freezes for 10-15 seconds when entering search terms with 5000+ results.

Yeah, I noticed this, too. I ll try to improve the loading process, so it wont block the browser.
- an option to set a custom/more useful startpage than the dashboard

I am planing to show some useful informations at the first page in the near futurre :)
- an option to hide the botlist in the local search tab, useful for when viewing on small displays

There is already an option ("Combine IRC View") which results into a single table where packets are grouped under their bots.

**Comment by hrvstr** [comment]
- be able to highlight the packetname in the webfrontend. (to copy/paste, google, search imdb, etc)
- Can you be more specific?
- When I browse the search results I often want so search youtube for a trailer or imdb for ratings. The current situation is that i can't highlight a packetname in the search results to use the context menu for a search. I would like to be able to use my mouse to highlight and copy the names so i don't have to type them everytime i don't know a file.
- You can click on the icon of a downloading packet and XG will stop the download process and clean up temporary files.
- just tried to click the file icon to cancel a running download. didn't seem to work. running XG2 on win8 pro x64 and viewing the webfrontend on macosx 10.8.2 with google chrome.

**Comment by Hamdor** [comment]
I can confirm that canceling download is broken, tested with lastest chrome, IE and opera
Using your last sources (09.07.2013)

**Comment by Hamdor** [comment]
OK i found the function to cancle downloads, it only works in the irc overview, but if you have a "dead" download (means that the bot gone offline) you cant cancel the download anymore...

**Comment by lformella** [comment]
@Hamdor your issue is solved here: https://github.com/lformella/xdcc-grabscher/releases/tag/v2.1.0

**Comment by hrvstr** [comment]
Canceling downloads by clicking the icon works now after applying the 2.1.0 update. Thanks!

**Comment by hrvstr** [comment]
another request: add a restart button to the settings drop-down menu.

this would be awesome as i have to constantly restart XG for two reasons:
- XG cant connect to any servers after the computer is being waken up from sleep-mode.
- search results sometimes won't come up and the cpu of the maschine viewing the web-frontend is under heavy load and getting extremly hot in a couple of second (from 60C to 95C).

**Comment by lformella** [comment]
I am running XG on a pc connected via dsl which is disconnected from the provider every day. XG handles this disconnection properly and reconnects to all servers. The machine running the web frontend goes to sleep regulary and after wakeup there pops up a small window in the frontend saying that you should reload the page. Because of the used websocket you have to reload the page after a disconnect - even if you lost your wlan signal. 

Which browser do you use? I noticed that chrome sometimes wont show the popup and thinks that he is connected, but you cant do anything.

**Comment by hrvstr** [comment]
I should have been more clear: i have set up my server to go to sleep mode after a certain time of inactivity (i use this tool: getsmartpower.co.uk). it basicly sends a suspend signal when the cpu or network usage have not hit a specified threshold in 10 minutes.

everything is working as expected when the maschine viewing the webfrontend goes to sleep.

**Comment by lformella** [comment]
@hrvstr packet name highlight bug is solved in: https://github.com/lformella/xdcc-grabscher/releases/tag/v2.1.1

**Comment by hrvstr** [comment]
Hm, doesn't seem to work here. I'm on 2.1.1. and i can only highlight the line in yellow to see the bot. Still can't select text to copy and paste or use the context menu.

**Comment by lformella** [comment]
you have to double click on a packet to open a box with its name - (by design you cant copy packet names in slick grid)

**Comment by hrvstr** [comment]
got it now, thanks for the help!

**Comment by lformella** [comment]
XG3 solves highlight and grid slow down issues (https://github.com/lformella/xdcc-grabscher/issues?milestone=3)
